from typing import List
from gordot.shapes import Shape

class OBJExporter:
    def __init__(self, shapes: List[Shape]):
        self.shapes = shapes

    def generate(self):
        string = '# .OBJ file generated by Gordot. Do not alter by hand unless you really know what you\'re doing \n\n'
        
        index = 1
        for i, shape in enumerate(self.shapes):
            string += f'g Object{i} \n'
            string += shape.export(index) + '\n'

            index += len(shape.points())

        return string 

    def write(self, path):
        with open(path, 'w') as file:
            string = self.generate()
            file.write(string)